codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  ignore:
    - "src/main/java/com/system/management/library/librarymanagementsystem/dto/*"  # ignore folders and all its contents
    - "src/main/java/com/system/management/library/librarymanagementsystem/views/*"
    - "src/main/java/com/system/management/library/librarymanagementsystem/LibraryManagementSystemApplication.java"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no