spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/dbchangelog.xml
    default-schema: public
  datasource:
    url: jdbc:h2:mem:library;DB_CLOSE_DELAY=-1
  h2:
    console:
      path: /h2
