version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw clean install -Pproduction
      - codecov/upload
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - target/*.jar

  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

workflows:
  build-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
