version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw clean install
      - codecov/upload

workflows:
  build-workflow:
    jobs:
      - build
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
