version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      web: Dockerfile
      worker: Dockerfile
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw clean install
      - codecov/upload
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web --arg NODE_ENV=production -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
  build-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
