version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - setup_remote_docker:
         version: 19.03.13
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw clean install
      - run: docker build -t webapp .
      - codecov/upload
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run: docker build .
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

workflows:
  build-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
