version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: chmod+x
      - run: ./mvnw clean install

workflows:
  build-workflow:
    jobs:
      - build
